apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "krply.fullname" . }}-args
  labels:
    {{- include "krply.labels" . | nindent 4 }}
data:
  STORE_PATH: {{ .Values.store.path | quote }}
  LISTEN_ADDR: ":{{ .Values.listen.port }}"
