apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "krply.fullname" . }}-args
  labels:
    {{- include "krply.labels" . | nindent 4 }}
data:
  store-path: {{ .Values.store.path | quote }}
  listen: ":{{ .Values.listen.port }}"
